# WARNING:
## DO NOT commit *iot-settings.yaml* file

settings:

  #### IOT presets
  presets:
    roof_water_heater:
      # [IotDeviceType] enum
      device_type: roof_water_heater

      # [int] [ms] the interval between each short term buzzer activity
      short_period_buzzer_interval_between_beep_ms: 000 # 0 sec

      # [int] [ms] the interval of activity after which the continuous alert buzzer should start.
      start_continuous_period_buzzer_beep_after_ms: 000 # 0 mins

      # [int] [ms] the duration of the short term buzzer beep
      short_period_buzzer_beep_duration_ms: 000 # 0 sec

      # [int] [ms] the maximum intervals allowed between iot activities to tag it as a single session
      # this is useful in judging whether the iot is still in session in case of a power failure or other unknown reasons.
      max_interval_to_persist_session_ms: 000 # 0 sec

    bore_well_motor:
      # [IotDeviceType] enum
      device_type: bore_well_motor

      # [int] [ms] the interval between each short term buzzer activity
      short_period_buzzer_interval_between_beep_ms: 000 # 0 sec

      # [int] [ms] the interval of activity after which the continuous alert buzzer should start.
      start_continuous_period_buzzer_beep_after_ms: 000 # 0 sec

      # [int] [ms] the duration of the short term buzzer beep
      short_period_buzzer_beep_duration_ms: 000 # 0 sec

      # [int] [ms] the maximum intervals allowed between iot activities to tag it as a single session
      # this is useful in judging whether the iot is still in session in case of a power failure or other unknown reasons.
      max_interval_to_persist_session_ms: 000 # 0 sec

    ground_well_motor:
      # [IotDeviceType] enum
      device_type: ground_well_motor

      # [int] [ms] the interval between each short term buzzer activity
      short_period_buzzer_interval_between_beep_ms: 000 # 0 sec

      # [int] [ms] the interval of activity after which the continuous alert buzzer should start.
      start_continuous_period_buzzer_beep_after_ms: 000 # 0 sec

      # [int] [ms] the duration of the short term buzzer beep
      short_period_buzzer_beep_duration_ms: 000 # 0 sec

      # [int] [ms] the maximum intervals allowed between iot activities to tag it as a single session
      # this is useful in judging whether the iot is still in session in case of a power failure or other unknown reasons.
      max_interval_to_persist_session_ms: 000 # 0 sec

